export const G_AUTH_CLIENT_ID = '995927193268-5eo1colbv3epna341ulqqosfr42tm9cn.apps.googleusercontent.com';
export const G_AUTH_CLIENT_SECRET = 'odjfeP3zpLY2GdohwyE2SnMY';
export const JWT_SECRET = 'addjsonwebtokensecretherelikeQuiscustodietipsoscustodes'
export const MONGO_PORT = 27017;
export const MONGO_LOCAL_CONN_URL = `mongodb://localhost:${MONGO_PORT}`;
export const MONGO_DB_NAME = 'Test'
export const MONGO_CLUSTER_USERNAME = 'g_chat_global';
export const MONGO_CLUSTER_PASSWORD = 'P1b2IpbqIgTr9lXm';
export const MONGO_CLUSTER_HOST = 'cluster0.i2yur.mongodb.net';
export const MONGO_CLUSTER_DB = 'GChat';
export const WHITE_LIST = ['http://localhost:9000', 'https://harikrishnankr.github.io']
